Repository wu-seong/MAP-homepage, pull requests merged in 2024-01, with the labels that each got.

#10 Chore/9
  build.gradle
  src/main/java/map/homepage/domain/Role.java
  src/main/resources/application-oauth2.yml
  src/main/resources/application.yml
Labels: :package: chore

#11 [FEATURE]: 소셜 로그인 구현 절반 완료
  src/main/java/map/homepage/auth/oauth2/CustomOAuth2UserService.java
  src/main/java/map/homepage/auth/oauth2/OAuthAttributes.java
  src/main/java/map/homepage/auth/oauth2/config/OAuth2ClientSecurityConfig.java
  src/main/java/map/homepage/auth/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/map/homepage/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/map/homepage/domain/Role.java
  src/main/java/map/homepage/domain/User.java
  src/main/java/map/homepage/domain/user/Role.java
  src/main/java/map/homepage/domain/user/User.java
  src/main/java/map/homepage/domain/user/UserRepository.java
  src/main/resources/application-oauth2.yml
Labels: :sparkles: feature

#19 [FEATURE]: 스프링 시큐리티 CORS 설정
  src/main/java/map/homepage/domain/member/auth/oauth2/config/OAuth2ClientSecurityConfig.java
Labels: :sparkles: feature

#24 [FEATURE]: 유저 엔티티 생성
  src/main/java/map/homepage/domain/member/Member.java
Labels: :sparkles: feature

#25 [FEATURE]: 유저 엔티티 생성
  src/main/java/map/homepage/HomepageApplication.java
  src/main/java/map/homepage/domain/common/BaseEntity.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/comment/Comment.java
Labels: :sparkles: feature

#29 [REFACTOR]: 소셜 로그인 시큐리티 없는 버전으로 리팩토링
  build.gradle
  src/main/java/map/homepage/HomepageApplication.java
  src/main/java/map/homepage/apiPayload/ApiResponse.java
  src/main/java/map/homepage/apiPayload/code/BaseCode.java
  src/main/java/map/homepage/apiPayload/code/ReasonDTO.java
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/apiPayload/code/status/SuccessStatus.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/MemberRepository.java
  src/main/java/map/homepage/domain/member/auth/MemberContext.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/controller/JwtController.java
  src/main/java/map/homepage/domain/member/auth/jwt/controller/TestController.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/CorsFilter.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/MemberInterceptor.java
  src/main/java/map/homepage/domain/member/auth/jwt/service/JwtTokenProvider.java
  src/main/java/map/homepage/domain/member/auth/jwt/service/JwtUtil.java
  src/main/java/map/homepage/domain/member/auth/oauth2/CustomOAuth2UserService.java
  src/main/java/map/homepage/domain/member/auth/oauth2/OAuthAttributes.java
  src/main/java/map/homepage/domain/member/auth/oauth2/config/OAuth2ClientSecurityConfig.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/CustomErrorDecoder.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/client/KakaoApiClient.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/client/KakaoOauth2Client.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/config/FeignConfig.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/ErrorResponseDTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/handler/OAuth2FailureHandler.java
  src/main/java/map/homepage/domain/member/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/map/homepage/domain/member/auth/oauth2/service/LoginService.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/dto/MemberResponseDTO.java
  src/main/java/map/homepage/domain/member/enums/SocialType.java
  src/main/java/map/homepage/domain/member/enums/Status.java
  src/main/java/map/homepage/domain/member/service/MemberService.java
  src/main/java/map/homepage/exception/ExceptionAdvice.java
  src/main/java/map/homepage/exception/GeneralException.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#30 [FEATURE]: 게시글 관련 API 구현
  src/main/java/map/homepage/HomepageApplication.java
  src/main/java/map/homepage/config/SwaggerConfig.java
  src/main/java/map/homepage/domain/common/BaseEntity.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostRepository.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/dto/PostRequestDTO.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/exception/MemberNotFoundException.java
  src/main/java/map/homepage/exception/PostNotFoundException.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#26 [FEATURE]: 유저 API 구현
  src/main/java/map/homepage/domain/Role.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/MemberController.java
  src/main/java/map/homepage/domain/member/MemberRepository.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/controller/JwtController.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/MemberInterceptor.java
  src/main/java/map/homepage/domain/member/auth/jwt/service/JwtUtil.java
  src/main/java/map/homepage/domain/member/auth/oauth2/OAuthAttributes.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/dto/MemberRequestDTO.java
  src/main/java/map/homepage/domain/member/dto/MemberResponseDTO.java
  src/main/java/map/homepage/domain/member/enums/Role.java
  src/main/java/map/homepage/domain/member/enums/Status.java
  src/main/java/map/homepage/domain/member/service/MemberCommandService.java
  src/main/java/map/homepage/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/map/homepage/domain/member/service/MemberQueryService.java
  src/main/java/map/homepage/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :test_tube: test

#31 [FEATURE]: 댓글 API 설계 & API 시그니처 만들기
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
  src/main/java/map/homepage/domain/post/comment/CommentRepository.java
  src/main/java/map/homepage/domain/post/comment/CommentService.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentCreateRequest.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentDto.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentReadCondition.java
  src/main/java/map/homepage/exception/MemberNotEqualsException.java
Labels: :sparkles: feature

#33 [FEATURE]: 네이버 로그인 구현
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/apiPayload/code/status/SuccessStatus.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/MemberRepository.java
  src/main/java/map/homepage/domain/member/auth/oauth2/OAuthAttributes.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/client/NaverApiClient.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/client/NaverOauth2Client.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/NaverOauth2DTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/service/LoginService.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/dto/MemberResponseDTO.java
  src/main/java/map/homepage/domain/member/service/MemberCommandService.java
  src/main/java/map/homepage/domain/member/service/MemberQueryService.java
  src/main/java/map/homepage/domain/member/service/MemberQueryServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :test_tube: test

#35 [FIX]: 프론트/Swagger 테스트 가능하도록 수정
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/auth/oauth2/service/LoginService.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/service/MemberCommandServiceImpl.java
Labels: :recycle: refactor, :test_tube: test

#39 [FEATURE]: 개발 배포용 CI/CD 설정 추가
  .github/workflows/dev_deploy.yml
Labels: :sparkles: feature, :rocket: CI/CD

#40 [CI-CD]: CI/CD 파이프 라인 구축
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/map/homepage/domain/common/controller/RootController.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
Labels: :sparkles: feature, :rocket: CI/CD

#42 [TEST]: CI/CD test
  src/main/java/map/homepage/domain/common/controller/RootController.java
Labels: :test_tube: test

#43 [TEST]: application.yml 한 파일에서 여러 파일로 분리 및 개발 인프라 설정 추가
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#44 [FIX]: 활성 프로필 dev로 변경
  src/main/resources/application.yml
Labels: :bug: bug
