Repository wu-seong/MAP-homepage, pull requests merged in 2024-02, with the labels that each got.

#45 [REFACTOR] 댓글 응답 통일 및 코드 리팩토링
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
  src/main/java/map/homepage/domain/post/comment/CommentService.java
  src/main/java/map/homepage/domain/post/comment/CommentServiceImpl.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentDto.java
Labels: :recycle: refactor

#48 [REFACTOR]: 게시글 api에서 member 변수 리팩토링
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/MemberInterceptor.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostRepository.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/dto/PostRequestDTO.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
Labels: :recycle: refactor

#52 [FEATRUE] 사진 게시판 기능 구현
  build.gradle
  src/main/java/map/homepage/config/AmazonConfig.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/domain/post/image/Image.java
  src/main/java/map/homepage/domain/post/image/ImageController.java
  src/main/java/map/homepage/domain/post/image/ImageRepository.java
  src/main/java/map/homepage/domain/post/image/ImageService.java
  src/main/java/map/homepage/domain/post/image/ImageServiceImpl.java
  src/main/java/map/homepage/exception/ImageUploadException.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature

#54 [FEATURE]: 관리자 기능 구현
  src/main/java/map/homepage/config/SwaggerConfig.java
  src/main/java/map/homepage/domain/member/auth/config/WebConfig.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/member/controller/AdminController.java
  src/main/java/map/homepage/domain/member/controller/MemberController.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/service/AdminCommandService.java
  src/main/java/map/homepage/domain/member/service/AdminCommandServiceImpl.java
Labels: :sparkles: feature

#56 [FEATURE]: 로그인 기능 수정, 응답 마다 토큰 갱신, 멤버 삭제 API 구현
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/MemberRepository.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/MemberInterceptor.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/service/MemberCommandService.java
  src/main/java/map/homepage/domain/member/service/MemberCommandServiceImpl.java
Labels: :sparkles: feature

#57 [fix]: delete -> softDelete로 수정
  src/main/java/map/homepage/domain/member/controller/MemberController.java
Labels: :bug: bug

#53 [Feature] 게시글 조회 구분, 공지 등록 및 해제
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostRepository.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/domain/post/image/ImageController.java
  src/main/java/map/homepage/exception/AccessDeniedException.java
Labels: :sparkles: feature

#51 [REFACTOR] 예외 처리 통일 & 댓글 조회 이슈
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
  src/main/java/map/homepage/domain/post/comment/CommentService.java
  src/main/java/map/homepage/domain/post/comment/CommentServiceImpl.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentReadCondition.java
Labels: :recycle: refactor

#60 Refactor: 페이징 및 응답통일
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostRepository.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/comment/CommentServiceImpl.java
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/PostResponseListDTO.java
  src/main/java/map/homepage/exception/AccessDeniedException.java
  src/main/java/map/homepage/exception/ImageUploadException.java
  src/main/java/map/homepage/exception/MemberNotFoundException.java
Labels: :recycle: refactor

#66 [FEATURE]: 기본 프로필 기능 추가, 로그인 응답에 권한정보 추가
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/ProfileImage.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/KakaoOauth2DTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/feignClient/dto/NaverOauth2DTO.java
  src/main/java/map/homepage/domain/member/auth/oauth2/service/LoginService.java
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/dto/MemberResponseDTO.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
  src/main/java/map/homepage/domain/post/image/Image.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#67 [FEATURE] 일반 게시글 첨부 파일 기능 추가
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/dto/PostRequestDTO.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/domain/post/image/ImageService.java
  src/main/java/map/homepage/domain/post/image/ImageServiceImpl.java
Labels: :sparkles: feature

#64 [REFACTOR] 댓글 최대 길이 설정
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
Labels: :recycle: refactor

#68 [FEATURE]: 댓글 유효성 검사 추가
  .ebextensions_dev/01-set-timezone.config
  build.gradle
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/domain/post/comment/Comment.java
  src/main/java/map/homepage/domain/post/comment/CommentController.java
  src/main/java/map/homepage/domain/post/comment/dto/CommentDto.java
  src/main/java/map/homepage/exception/validation/annotation/CommentValidation.java
  src/main/java/map/homepage/exception/validation/validator/CommentValidator.java
Labels: :bug: bug, :sparkles: feature

#76 [FEATURE]: 유저정보 조회 API 수정
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/domain/member/Member.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/member/auth/oauth2/controller/LoginController.java
  src/main/java/map/homepage/domain/member/controller/AdminController.java
  src/main/java/map/homepage/domain/member/controller/MemberController.java
  src/main/java/map/homepage/domain/member/profileImage/ProfileImage.java
  src/main/java/map/homepage/domain/member/profileImage/repository/ProfileImageRepository.java
  src/main/java/map/homepage/domain/member/service/AdminCommandService.java
  src/main/java/map/homepage/domain/member/service/AdminCommandServiceImpl.java
  src/main/java/map/homepage/domain/member/service/MemberQueryServiceImpl.java
Labels: :bug: bug, :sparkles: feature

#77 [FIX]: 페이징 생각하기 쉽도록 1페이지 부터 시작하도록 받는걸로 수정
  src/main/java/map/homepage/domain/member/controller/AdminController.java
  src/main/java/map/homepage/domain/member/controller/MemberController.java
Labels: :sparkles: feature

#81 [REFACTOR]: 게시글 전반적인 리팩토링
  src/main/java/map/homepage/domain/member/auth/jwt/service/JwtUtil.java
  src/main/java/map/homepage/domain/member/profileImage/ProfileImage.java
  src/main/java/map/homepage/domain/post/Post.java
  src/main/java/map/homepage/domain/post/PostController.java
  src/main/java/map/homepage/domain/post/PostService.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/attachedFile/AttachedFile.java
  src/main/java/map/homepage/domain/post/attachedFile/converter/AttachedFileConverter.java
  src/main/java/map/homepage/domain/post/attachedFile/dto/AttachedFileResponseDTO.java
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
  src/main/java/map/homepage/domain/post/dto/PostResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/general/GeneralPostPreviewResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/general/GeneralPostPreviewResponseListDTO.java
  src/main/java/map/homepage/domain/post/dto/general/GeneralPostResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/photo/PhotoPostPreviewResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/photo/PhotoPostPreviewResponseListDTO.java
  src/main/java/map/homepage/domain/post/dto/photo/PhotoPostResponseDTO.java
  src/main/java/map/homepage/domain/post/image/FileManagementService.java
  src/main/java/map/homepage/domain/post/image/FileManagementServiceImpl.java
  src/main/java/map/homepage/domain/post/image/ImageController.java
  src/main/java/map/homepage/domain/post/image/ImageService.java
  src/main/java/map/homepage/domain/post/image/converter/ImageConverter.java
  src/main/java/map/homepage/domain/post/image/dto/ImageResponseDTO.java
  src/main/java/map/homepage/domain/post/image/dto/ImageResponseListDTO.java
  src/main/resources/application-dev.yml
Labels: :recycle: refactor

#82 [FIX]: 첨부파일 존재 하지 않을 경우 null예외 해결
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
Labels: :bug: bug

#83 [FIX]: 일반게시글 previewResponseDTO에서 첨부파일 관련 코드 삭제
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
Labels: :bug: bug

#84 [FIX]: 첨부파일 save 주석처리 해제
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
Labels: :bug: bug

#85 [FIX]: 게시판 오류 해결
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
  src/main/java/map/homepage/domain/post/dto/general/GeneralPostPreviewResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/photo/PhotoPostPreviewResponseDTO.java
  src/main/java/map/homepage/domain/post/dto/photo/PhotoPostPreviewResponseListDTO.java
Labels: :bug: bug

#86 [FEATURE]: 사진목록 조회 DTO에 컨버터에 사진 목록 추가
  src/main/java/map/homepage/domain/post/converter/PostConverter.java
Labels: :sparkles: feature

#87 [REFACTOR]: 사진게시판 리팩토링
  src/main/java/map/homepage/apiPayload/code/status/ErrorStatus.java
  src/main/java/map/homepage/domain/member/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/map/homepage/domain/post/PostServiceImpl.java
  src/main/java/map/homepage/domain/post/image/FileManagementService.java
  src/main/java/map/homepage/domain/post/image/FileManagementServiceImpl.java
Labels: :recycle: refactor

#89 [FEATURE]: 로그인 응답에 이름/닉네임 추가
  src/main/java/map/homepage/domain/member/converter/MemberConverter.java
  src/main/java/map/homepage/domain/member/dto/MemberResponseDTO.java
Labels: :sparkles: feature
